mpremote connect COM19 fs cp chanceflurries.png :res/chanceflurries.png &&
mpremote connect COM19 fs cp chancerain.png :res/chancerain.png &&
mpremote connect COM19 fs cp chancesleet.png :res/chancesleet.png &&
mpremote connect COM19 fs cp chancesnow.png :res/chancesnow.png &&
mpremote connect COM19 fs cp chancetstorms.png :res/chancetstorms.png &&
mpremote connect COM19 fs cp clear.png :res/clear.png &&
mpremote connect COM19 fs cp cloudy.png :res/cloudy.png &&
mpremote connect COM19 fs cp flurries.png :res/flurries.png &&
mpremote connect COM19 fs cp fog.png :res/fog.png &&
mpremote connect COM19 fs cp hazy.png :res/hazy.png &&
mpremote connect COM19 fs cp mostlycloudy.png :res/mostlycloudy.png &&
mpremote connect COM19 fs cp mostlysunny.png :res/mostlysunny.png &&
mpremote connect COM19 fs cp nt_chanceflurries.png :res/nt_chanceflurries.png &&
mpremote connect COM19 fs cp nt_chancerain.png :res/nt_chancerain.png &&
mpremote connect COM19 fs cp nt_chancesleet.png :res/nt_chancesleet.png &&
mpremote connect COM19 fs cp nt_chancesnow.png :res/nt_chancesnow.png &&
mpremote connect COM19 fs cp nt_chancetstorms.png :res/nt_chancetstorms.png &&
mpremote connect COM19 fs cp nt_clear.png :res/nt_clear.png &&
mpremote connect COM19 fs cp nt_cloudy.png :res/nt_cloudy.png &&
mpremote connect COM19 fs cp nt_flurries.png :res/nt_flurries.png &&
mpremote connect COM19 fs cp nt_fog.png :res/nt_fog.png &&
mpremote connect COM19 fs cp nt_hazy.png :res/nt_hazy.png &&
mpremote connect COM19 fs cp nt_mostlycloudy.png :res/nt_mostlycloudy.png &&
mpremote connect COM19 fs cp nt_mostlysunny.png :res/nt_mostlysunny.png &&
mpremote connect COM19 fs cp nt_partlycloudy.png :res/nt_partlycloudy.png &&
mpremote connect COM19 fs cp nt_partlysunny.png :res/nt_partlysunny.png &&
mpremote connect COM19 fs cp nt_rain.png :res/nt_rain.png &&
mpremote connect COM19 fs cp nt_sleet.png :res/nt_sleet.png &&
mpremote connect COM19 fs cp nt_snow.png :res/nt_snow.png &&
mpremote connect COM19 fs cp nt_sunny.png :res/nt_sunny.png &&
mpremote connect COM19 fs cp nt_tstorms.png :res/nt_tstorms.png &&
mpremote connect COM19 fs cp nt_unknown.png :res/nt_unknown.png &&
mpremote connect COM19 fs cp partlycloudy.png :res/partlycloudy.png &&
mpremote connect COM19 fs cp partlysunny.png :res/partlysunny.png &&
mpremote connect COM19 fs cp rain.png :res/rain.png &&
mpremote connect COM19 fs cp sleet.png :res/sleet.png &&
mpremote connect COM19 fs cp snow.png :res/snow.png &&
mpremote connect COM19 fs cp sunny.png :res/sunny.png &&
mpremote connect COM19 fs cp tstorms.png :res/tstorms.png &&
mpremote connect COM19 fs cp unknown.png :res/unknown.png